### ISSUE TITLE
Permission error when I try to use the snap adding

### ISSUE THREAD

**Issue by konceptnet** [AlfMikael/snap-generator#2]
When I try to use the cantilever addin here is the message I got 👍 
![image](https://user-images.githubusercontent.com/53401670/141210889-6403992b-6055-4d15-b83d-592584456dd7.png)

Can you help me to make it work please

**Comment by AlfMikael** [comment]
Hi, this is a bug that I have not fixed yet. I think it happens because the addin doesn't have permission to create a file that it needs in your app data folder. I can try to fix the code tomorrow, but for now it might be possible to make it work by running fusion 360 in administrator mode. Then it might be able to create the file. After that, administration mode shouldn't be necessary I think.

**Comment by konceptnet** [comment]
If you could look at it, I very apreciate. I try running it admin privilege but I got the same error. I try : right click on the executable then select run as administrator

**Comment by AlfMikael** [comment]
I just released a new version which hopefully resolved the issue :)

**Comment by konceptnet** [comment]
It works, I re-install it from the zip file and also go to delete the Snap Generator - Fusion 360 addin folder into the %appdata%\local

**Comment by konceptnet** [comment]
I try to play with the cantilever, but I need to do a smal one, can you help me with all the variable ? Would you like to add me on facebook ?

**Comment by AlfMikael** [comment]
I would not advise you make the length any shorter than 10mm, or you might have trouble printing it. The default settings will give you a cantilever that is almost as small as possible.
