### ISSUE TITLE
not working with all of the versions

### ISSUE THREAD

**Issue by GiulioVenuti** [AlfMikael/snap-generator#6]
I tried with every version but they don't appear in the add-ins.

**Comment by AlfMikael** [comment]
@GiulioVenuti  Did you unzip the files?

**Comment by ishiharas** [comment]
@GiulioVenuti 
Did you by any chance rename the unzipped folder, before moving it to the AddIns folder?

@AlfMikael 
Because I surely did and renamed it from snap-generator-v0.2.1 to snap-generator.
Afterwards fusion360 wasn't able to find the plugin at all. 

I unzipped it a second time, while leaving everything as is. And the second folder shows up in my addIn list.

**Comment by GiulioVenuti** [comment]
I solved it but with a different method.

I created an add-in directly from fusion 360 then deleted everything inside that folder and pasted inside the folder your add-in. I then copied the name of your folder onto mine.

I managed to run the add-in only in that way.

I suggest you to write also this method of install.

**Comment by AlfMikael** [comment]
> 

Isn't that the exact same thing as just copying the folder directly into the add-in folder? As far as I know, making a new addon this way and copying the name has no effect. It's the same as just copying the folder. Maybe I'm wrong though, but copying the folder has never failed to work for me whenever I have installed add-ins.
